import React from 'react';

import '../menu.css';
export default function GameOverMenu(props) {

    return (
        <div className='menu'>
            <h2>Game Over</h2>
            <p>You have caused an excessive amount of nitrogen runoff. The government has stepped in and shut down your farm.</p>
            <p>Tip: Keep an eye on your nitrogen runoff concentration. Nitrogen runoff is generated by fertilizing plants, placing nitrogen fixators, and failing to maintain ammonium silos.</p>
            <div className='controls'>
                <button onClick={() => location.reload()}>
                    Retry
                </button>
            </div>
        </div>
    );
}



