import React from 'react';
import { menus, setActiveMenu } from '..';

import '../menu.css';
export default function GameOverMenu(props) {

    return (
        <div className='menu'>
            <h2>Game Over</h2>
            <p>You have caused an excessive amount of nitrogen runoff. The envrionment has become oversaturated with nitrogen. The government has stepped in and shut down your farm.</p>
            <p>You can keep playing for now, but try not to produce any more nitrogen runoff.</p>
            <p>If you would like to retry, refresh the page.</p>
            <p>Tip: Keep an eye on your nitrogen runoff concentration. Nitrogen runoff is generated by fertilizing plants, placing nitrogen fixators, and failing to maintain ammonium silos.</p>
            <div className='controls'>
                <button className='close' onClick={() => setActiveMenu(menus.none)}>Close</button>
            </div>
        </div>
    );
}



